server:
  port: 9030
  shutdown: graceful

spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
  datasource:
    type: org.apache.commons.dbcp2.BasicDataSource
    dbcp2:
      driver-class-name:
      url: jdbc:mysql://133.186.241.167:3306/aling_post_dev?characterEncoding=UTF-8
      username: aling
      password: r]0T5NWLu*fRv!4P
      max-idle: 2
      max-total: 2
      min-idle: 2
      initial-size: 2
      validation-query: select 1
      test-on-borrow: true
