:toc:

==== 게시글 존재 여부 조회

게시글 번호 기준 존재 여부 조회 API

===== 요청

operation::post-is-exists-post[snippets='http-request']

===== 응답

operation::post-is-exists-post[snippets='http-response']

====== 파라미터 설명

====== 요청 Path Param

operation::post-is-exists-post[snippets='path-parameters']

====== 응답 Body

operation::post-is-exists-post[snippets='response-fields']


==== 스크랩용 게시글 조회

게시글 번호 리스트 기준 게시글 조회 API

===== 요청

operation::post-read-for-scrap[snippets='http-request']

===== 응답

operation::post-read-for-scrap[snippets='http-response']

====== 파라미터 설명

====== 요청 Params

operation::post-read-for-scrap[snippets='request-parameters']

====== 응답 Body

operation::post-read-for-scrap[snippets='response-fields']

==== 게시글 단건 조회

게시글 단건 조회 API

===== 요청

operation::post-single-get[snippets='http-request']

===== 응답

operation::post-single-get[snippets='http-response']

===== 파라미터 설명

====== 응답 Body

operation::post-single-get[snippets='response-fields']

==== 게시글 (여러개) 조회

여러 게시글 조회 API

===== 요청

operation::post-paging-get[snippets='http-request']

===== 응답

operation::post-paging-get[snippets='http-response']

===== 파라미터 설명

====== 응답 Body 

operation::post-paging-get[snippets='response-fields']

==== 회원별 일반 게시글 조회

회원이 작성한 일반 게시글 조회 API

===== 요청

operation::post-normal-byUser-get[snippets='http-request']

===== 응답

operation::post-normal-byUser-get[snippets='http-response']

===== 파라미터 설명

====== 응답 Body 

operation::post-normal-byUser-get[snippets='response-fields']

==== 회원별 그룹 게시글 조회

회원이 작성한 그룹 게시글 조회 API

===== 요청

operation::post-band-byUser-get[snippets='http-request']

===== 응답

operation::post-band-byUser-get[snippets='http-response']

===== 파라미터 설명

====== 응답 Body

operation::post-band-byUser-get[snippets='response-fields']

